CREATE DATABASE  IF NOT EXISTS `loja_virtual`;
USE `loja_virtual`;

DROP TABLE IF EXISTS `categoria`;

CREATE TABLE `categoria` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOCK TABLES `categoria` WRITE;

INSERT INTO `categoria` VALUES (1,'ELETRONICOS'),(2,'ELETRODOMESTICOS'),(3,'MOVEIS');

UNLOCK TABLES;

DROP TABLE IF EXISTS `produto`;

CREATE TABLE `produto` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(50) NOT NULL,
  `descricao` varchar(255) DEFAULT NULL,
  `CATEGORIA_ID` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `CATEGORIA_ID` (`CATEGORIA_ID`),
  CONSTRAINT `produto_ibfk_1` FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `categoria` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOCK TABLES `produto` WRITE;

INSERT INTO `produto` VALUES (1,'NOTEBOOK','NOTEBOOK SAMSUNG',1),(2,'GELADEIRA','GELADEIRA AZUL',2),(21,'Cômoda','Cômoda Vertical',3);

UNLOCK TABLES;
